version: '3.8'

services:
#iniciaros serviços do node
  node_app:
    build:
      context: ./API
      #procurar o arquivo dockerfile
      dockerfile: Dockerfile
    #porta API quando subir
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    build:
      context: ./Mongo
      dockerfile: Dockerfile
    networks:
      - backend

networks:
  backend:
    driver: bridge
