
#imagem do dockerhub
FROM mongo:latest

#expor qual a porta 
EXPOSE 27018

#DIRETÓRIO C:\Users\Karla Duarte\Documents\docker\mongodb
WORKDIR C:/Users/Karla Duarte/Documents/docker/mongodb/

CMD ["mongod", "--port", "27018"]